language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - cp magpie.ini.example magpie.ini
before_script:
  - pip install coverage python-coveralls
script:
  - coverage run --source="magpie/" --omit=magpie/wsgi.py manage.py test
after_success:
  - coveralls
